[package]
name = "doom"
version = "0.1.0"
authors = ["Christopher Butcher <cbutcher@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.3.4"
svg = "0.6.0"
nalgebra-glm = "0.7.0"
lyon = "0.15.6"
png = "0.16.3"

# New deps, as of gfx-rs backend swap
image = "0.23"
winit = "0.22"
shaderc = "0.6"
cgmath = "0.17"
failure = "0.1"
tobj = "1.0.0"
wgpu = "0.5.0"
futures = "0.3.4"
bytemuck = "1.2.0"