[package]
name = "doom"
version = "0.1.0"
authors = ["Christopher Butcher <cbutcher@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# vulkano = "0.17.0"
# vulkano-shaders = "0.17.0"
# winit = "0.21.0"
# vulkano-win = "0.17.0"

# kiss3d = "0.22.1"
# nalgebra = "0.19.0"

# three = "0.4.0"

regex = "1.3.4"

glium = "0.26.0"
image = "0.23.0"
