[package]
name = "doom"
version = "0.1.0"
authors = ["Christopher Butcher <cbutcher@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.4.3"
svg = "0.9.0"
nalgebra-glm = "0.7.0"
lyon = "0.17.5"
png = "0.16.8"

# New deps, as of gfx-rs backend swap
image = "0.23.13"
winit = "0.24.0"
shaderc = "0.7.1"
cgmath = "0.18.0"
failure = "0.1.8"
tobj = "2.0.4"
wgpu = "0.6.0"
futures = "0.3.13"
env_logger = "0.7"
log = "0.4.14"