[package]
name = "doom"
version = "0.1.0"
authors = ["Christopher Butcher <cbutcher@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.3.4"
glium = "0.26.0"
image = "0.23.0"
svg = "0.6.0"
nalgebra-glm = "0.7.0"
lyon = "0.15.6"
png = "0.16.3"